### ISSUE TITLE
Internal server error showing up on many other pages now

### ISSUE THREAD

**Issue by waa** [domenkozar/almir#31]
This is the log when I client the Dashboard now. 

2012-04-06 15:46:59,045 ERROR [exc_logger][Dummy-1] http://almir.revpol.com:8000/
Traceback (most recent call last):
  File "/opt/almir/eggs/pyramid_exclog-0.5-py2.7.egg/pyramid_exclog/**init**.py", line 40, in exclog_tween
    return handler(request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/config/views.py", line 352, in rendered_view
    context)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 396, in render_view
    return self.render_to_response(response, system, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 426, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 422, in render
    result = renderer(value, system_values)
  File "/opt/almir/eggs/pyramid_jinja2-1.3-py2.7.egg/pyramid_jinja2/**init**.py", line 287, in **call**
    return self.template.render(system)
  File "/opt/almir/eggs/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/almir/almir/templates/dashboard.jinja2", line 1, in top-level template code
    {% extends "templates/base.jinja2" %}
  File "/opt/almir/almir/templates/base.jinja2", line 73, in top-level template code
    {% block container %}
  File "/opt/almir/almir/templates/base.jinja2", line 84, in block "container"
    {% block content %}
  File "/opt/almir/almir/templates/dashboard.jinja2", line 13, in block "content"
    {{ macros.jobs_table(request, jobs) }}
  File "/opt/almir/almir/templates/macros.jinja2", line 67, in template
    <td>{{ link(job.render_type(request)) }}</td>
  File "/opt/almir/almir/models.py", line 249, in render_type
    return {'text': TYPES[self.type]}
KeyError: 'C'
2012-04-06 15:46:59,048 ERROR [waitress][Dummy-1] Exception when serving /
Traceback (most recent call last):
  File "/opt/almir/eggs/waitress-0.8.1-py2.7.egg/waitress/channel.py", line 329, in service
    task.service()
  File "/opt/almir/eggs/waitress-0.8.1-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/opt/almir/eggs/waitress-0.8.1-py2.7.egg/waitress/task.py", line 380, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/router.py", line 187, in **call**
    response = self.handle_request(request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/opt/almir/eggs/pyramid_tm-0.3-py2.7.egg/pyramid_tm/**init**.py", line 61, in tm_tween
    response = handler(request)
  File "/opt/almir/eggs/pyramid_exclog-0.5-py2.7.egg/pyramid_exclog/**init**.py", line 40, in exclog_tween
    return handler(request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/config/views.py", line 352, in rendered_view
    context)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 396, in render_view
    return self.render_to_response(response, system, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 426, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 422, in render
    result = renderer(value, system_values)
  File "/opt/almir/eggs/pyramid_jinja2-1.3-py2.7.egg/pyramid_jinja2/**init**.py", line 287, in **call**
    return self.template.render(system)
  File "/opt/almir/eggs/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/almir/almir/templates/dashboard.jinja2", line 1, in top-level template code
    {% extends "templates/base.jinja2" %}
  File "/opt/almir/almir/templates/base.jinja2", line 73, in top-level template code
    {% block container %}
  File "/opt/almir/almir/templates/base.jinja2", line 84, in block "container"
    {% block content %}
  File "/opt/almir/almir/templates/dashboard.jinja2", line 13, in block "content"
    {{ macros.jobs_table(request, jobs) }}
  File "/opt/almir/almir/templates/macros.jinja2", line 67, in template
    <td>{{ link(job.render_type(request)) }}</td>
  File "/opt/almir/almir/models.py", line 249, in render_type
    return {'text': TYPES[self.type]}
KeyError: 'C'
2012-04-06 15:47:00,151 ERROR [exc_logger][Dummy-2] http://127.0.0.1:2500/
Traceback (most recent call last):
  File "/opt/almir/eggs/pyramid_exclog-0.5-py2.7.egg/pyramid_exclog/**init**.py", line 40, in exclog_tween
    return handler(request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/config/views.py", line 352, in rendered_view
    context)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 396, in render_view
    return self.render_to_response(response, system, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 426, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 422, in render
    result = renderer(value, system_values)
  File "/opt/almir/eggs/pyramid_jinja2-1.3-py2.7.egg/pyramid_jinja2/**init**.py", line 287, in **call**
    return self.template.render(system)
  File "/opt/almir/eggs/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/almir/almir/templates/dashboard.jinja2", line 1, in top-level template code
    {% extends "templates/base.jinja2" %}
  File "/opt/almir/almir/templates/base.jinja2", line 73, in top-level template code
    {% block container %}
  File "/opt/almir/almir/templates/base.jinja2", line 84, in block "container"
    {% block content %}
  File "/opt/almir/almir/templates/dashboard.jinja2", line 13, in block "content"
    {{ macros.jobs_table(request, jobs) }}
  File "/opt/almir/almir/templates/macros.jinja2", line 67, in template
    <td>{{ link(job.render_type(request)) }}</td>
  File "/opt/almir/almir/models.py", line 249, in render_type
    return {'text': TYPES[self.type]}
KeyError: 'C'
2012-04-06 15:47:00,154 ERROR [waitress][Dummy-2] Exception when serving /
Traceback (most recent call last):
  File "/opt/almir/eggs/waitress-0.8.1-py2.7.egg/waitress/channel.py", line 329, in service
    task.service()
  File "/opt/almir/eggs/waitress-0.8.1-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/opt/almir/eggs/waitress-0.8.1-py2.7.egg/waitress/task.py", line 380, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/router.py", line 187, in **call**
    response = self.handle_request(request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/opt/almir/eggs/pyramid_tm-0.3-py2.7.egg/pyramid_tm/**init**.py", line 61, in tm_tween
    response = handler(request)
  File "/opt/almir/eggs/pyramid_exclog-0.5-py2.7.egg/pyramid_exclog/**init**.py", line 40, in exclog_tween
    return handler(request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/config/views.py", line 352, in rendered_view
    context)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 396, in render_view
    return self.render_to_response(response, system, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 426, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/opt/almir/eggs/pyramid-1.3-py2.7.egg/pyramid/renderers.py", line 422, in render
    result = renderer(value, system_values)
  File "/opt/almir/eggs/pyramid_jinja2-1.3-py2.7.egg/pyramid_jinja2/**init**.py", line 287, in **call**
    return self.template.render(system)
  File "/opt/almir/eggs/Jinja2-2.6-py2.7.egg/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/almir/almir/templates/dashboard.jinja2", line 1, in top-level template code
    {% extends "templates/base.jinja2" %}
  File "/opt/almir/almir/templates/base.jinja2", line 73, in top-level template code
    {% block container %}
  File "/opt/almir/almir/templates/base.jinja2", line 84, in block "container"
    {% block content %}
  File "/opt/almir/almir/templates/dashboard.jinja2", line 13, in block "content"
    {{ macros.jobs_table(request, jobs) }}
  File "/opt/almir/almir/templates/macros.jinja2", line 67, in template
    <td>{{ link(job.render_type(request)) }}</td>
  File "/opt/almir/almir/models.py", line 249, in render_type
    return {'text': TYPES[self.type]}
KeyError: 'C'

**Comment by domenkozar** [comment]
This should be fixed with #4
