### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by matthijs** [domenkozar/almir#38]
Hi,

I get sometimes the error printed below. This is happening when I click on a client. This only
happens when there are no Jobs for that client.

2012-05-07 13:25:54,252 ERROR [waitress][Dummy-4] Exception when serving /client/26/
Traceback (most recent call last):
  File "/srv/www/bacula/eggs/waitress-0.8.1-py2.6.egg/waitress/channel.py", line 329, in service
    task.service()
  File "/srv/www/bacula/eggs/waitress-0.8.1-py2.6.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/srv/www/bacula/eggs/waitress-0.8.1-py2.6.egg/waitress/task.py", line 380, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/srv/www/bacula/eggs/pyramid-1.3-py2.6.egg/pyramid/router.py", line 187, in **call**
    response = self.handle_request(request)
  File "/srv/www/bacula/eggs/pyramid-1.3-py2.6.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/srv/www/bacula/eggs/pyramid_tm-0.3-py2.6.egg/pyramid_tm/**init**.py", line 61, in tm_tween
    response = handler(request)
  File "/srv/www/bacula/eggs/pyramid_exclog-0.5-py2.6.egg/pyramid_exclog/**init**.py", line 40, in exclog_tween
    return handler(request)
  File "/srv/www/bacula/eggs/pyramid-1.3-py2.6.egg/pyramid/router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "/srv/www/bacula/eggs/pyramid-1.3-py2.6.egg/pyramid/config/views.py", line 352, in rendered_view
    context)
  File "/srv/www/bacula/eggs/pyramid-1.3-py2.6.egg/pyramid/renderers.py", line 396, in render_view
    return self.render_to_response(response, system, request=request)
  File "/srv/www/bacula/eggs/pyramid-1.3-py2.6.egg/pyramid/renderers.py", line 426, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/srv/www/bacula/eggs/pyramid-1.3-py2.6.egg/pyramid/renderers.py", line 422, in render
    result = renderer(value, system_values)
  File "/srv/www/bacula/eggs/pyramid_jinja2-1.3-py2.6.egg/pyramid_jinja2/**init**.py", line 287, in **call**
    return self.template.render(system)
  File "/srv/www/bacula/eggs/Jinja2-2.6-py2.6.egg/jinja2/environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/www/bacula/almir/templates/client_detail.jinja2", line 1, in top-level template code
    {% extends "templates/base.jinja2" %}
  File "/srv/www/bacula/almir/templates/base.jinja2", line 73, in top-level template code
    {% block container %}
  File "/srv/www/bacula/almir/templates/base.jinja2", line 76, in block "container"
    {% block sidebar %}
  File "/srv/www/bacula/almir/templates/client_detail.jinja2", line 24, in block "sidebar"
    <td>{{ macros.link(last_successful_job[0].render_starttime(request)) }}</td>
UndefinedError: 'None' has no attribute 'render_starttime'

Regards,

Matthijs Möhlmann

**Comment by domenkozar** [comment]
Fixed in issue #4, I will release 0.1.2 soon!
