### ISSUE TITLE
PostgreSQL and configuration issue

### ISSUE THREAD

**Issue by vkl56** [domenkozar/almir#62]
Hello,

I have an issue during almir installation:

 Configuring almir ... If you want to use the default value (where possible), press enter.

<pre><code>
--> Host to listen on (default: 127.0.0.1): 
--> Port to listen on (default: 2500): 

Define SQL database connection to bacula catalog as specified in http://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls
For example:
    postgresql+pg8000://<user>:<password>@<hostname>/<database>
    mysql+mysqlconnector://<user>:<password>@<hostname>/<database>
    sqlite:////var/lib/bacula/bacula.db
    sqlite:///bacula.db

--> SQL connection string: postgresql+pg8000://user:pass@pgsql_server/dbname
Connecting to catalog database to verify configuration ...
    Try again: invalid literal for int() with base 10: 'SELECT'
</code></pre>

Any idea?

PostgreSQL: 8.4.x

**Comment by domenkozar** [comment]
What if you run:

```
import sqlalchemy
print sqlalchemy.create_engine("postgresql+pg8000://user:pass@pgsql_server/dbname")
```

in python interpreter?

**Comment by vkl56** [comment]
On 14/01/2014 19:43, Domen Kožar wrote:

> What if you run:
> 
> |import sqlalchemy
> print sqlalchemy.create_engine("postgresql+pg8000://user:pass@pgsql_server/dbname")
> |
> 
> in python interpreter?

2014-01-22 11:32:32,251 INFO sqlalchemy.engine.base.Engine select version()
INFO:sqlalchemy.engine.base.Engine:select version()
2014-01-22 11:32:32,253 INFO sqlalchemy.engine.base.Engine ()
INFO:sqlalchemy.engine.base.Engine:()
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 
2458, in connect
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 
881, in **init**
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 
2544, in raw_connection
   File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 183, in 
unique_connection
   File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 387, in 
**init**
   File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 739, in 
_do_get
   File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 188, in 
_create_connection
   File "build/bdist.linux-x86_64/egg/sqlalchemy/pool.py", line 273, in 
__init__
   File "build/bdist.linux-x86_64/egg/sqlalchemy/event.py", line 282, in 
exec_once
   File "build/bdist.linux-x86_64/egg/sqlalchemy/event.py", line 291, in 
**call**
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/strategies.py", 
line 167, in first_connect
   File 
"build/bdist.linux-x86_64/egg/sqlalchemy/dialects/postgresql/base.py", 
line 988, in initialize
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", 
line 175, in initialize
   File 
"build/bdist.linux-x86_64/egg/sqlalchemy/dialects/postgresql/base.py", 
line 1172, in _get_server_version_info
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 
1450, in execute
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 
1627, in _execute_text
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 
1690, in _execute_context
   File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", 
line 335, in do_execute
   File "build/bdist.linux-x86_64/egg/pg8000/core.py", line 402, in execute
   File "build/bdist.linux-x86_64/egg/pg8000/core.py", line 1960, in execute
   File "build/bdist.linux-x86_64/egg/pg8000/core.py", line 1383, in bind
   File "build/bdist.linux-x86_64/egg/pg8000/core.py", line 1470, in 
handle_messages
   File "build/bdist.linux-x86_64/egg/pg8000/core.py", line 1439, in 
handle_COMMAND_COMPLETE
ValueError: invalid literal for int() with base 10: 'SELECT'

**Comment by domenkozar** [comment]
Could you also print `sqlalchemy.__version__`?

**Comment by domenkozar** [comment]
Aha according to https://github.com/mfenniak/pg8000/issues/22#issuecomment-30761635 you should upgrade pg8000 to 1.9.2

**Comment by Teepareep** [comment]
I have this same issue

```
# uname -r
2.6.32-504.1.3.el6.x86_64
# rpm -qa | grep -i postg
postgresql-libs-8.4.20-1.el6_5.x86_64
postgresql-8.4.20-1.el6_5.x86_64
postgresql-server-8.4.20-1.el6_5.x86_64
bacula-director-postgresql-5.0.0-12.el6.x86_64
postgresql-devel-8.4.20-1.el6_5.x86_64
bacula-storage-postgresql-5.0.0-12.el6.x86_64
```

```
>>> import pg8000
>>> pg8000.__version__
'1.10.1'
>>> sqlalchemy.__version__
'0.9.8'
>>> print sqlalchemy.create_engine("postgresql+pg8000://postgres:password@localhost/bacula")
Engine(postgresql+pg8000://postgres:***@localhost/bacula)
```

```
--> SQL connection string: postgresql+pg8000://postgres:password@localhost/bacula
Connecting to catalog database to verify configuration ...
    Try again: invalid literal for int() with base 10: 'SELECT'
```

**Comment by domenkozar** [comment]
Would someone be willing to bump pg8000 version and test it, then submit a PR?
